name = "bloggy-api"
main = "src/index.js"
compatibility_date = "2023-01-12"

kv_namespaces = [
  { binding = "AKV", id = "854c863c76a548e491b1141a6dcd9439" },
	{ binding = "PKV", id = "60f81627fcdb46f19064d93be33765b6" }
]

[[d1_databases]]
binding = "DB"
database_name = "bloggy"
database_id = "92ee90cf-925c-423c-b66b-57ec81663c1e"

[[r2_buckets]]
binding = 'R2'
bucket_name = 'bloggy'

[triggers]
crons = ["0 */1 * * *"]

[vars]
DOMAIN = "https://bloggy.io"
CDN = "https://cdn.bloggy.io"
TITLE = "Bloggy"
DESCRIPTION = "Simple and open source network for creators"
AUTHOR = "Rabbit Company"
ANALYTICS = "<script defer data-domain='bloggy.io' src='https://analytics.rabbit-company.com/js/plausible.js'></script>"
LANGUAGE = "en"
# Optional variables
WEBSITE = "https://rabbit-company.com"
DISCORD = "https://discord.rabbit-company.com"
TWITTER = "https://twitter.com/RabbitCompany66"
GITHUB = "https://github.com/Rabbit-Company"
EMAIL = "info@rabbit-company.com"
# Don't forget to set the secret TOKEN with: wrangler secret put TOKEN